name: "Create Release"
on:
  push:
    tags:
      - "*"
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 21
          cache: maven
      - name: Build with Maven
        run: mvn clean install
      - name: Get The Version
        id: version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ steps.version.outputs.VERSION }}
          draft: true
          files: |
            Plugin/target/DisguiseAPI.jar
            API/target/API-*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}